### ISSUE TITLE
Bubbles placement

### ISSUE THREAD

**Issue by roos-robert** [HomeSharp/Iris#6]
The bubbles that are beeing written for the Iris module, shouldn't they be placed at the appropriate repositorium. Netatmo at: https://github.com/HomeSharp/Bubbles-Netatmo for example?

**Comment by vl222cu** [comment]
Yes, that's the plan :) We actually discussed this in yesterday's SCRUM-meeting that we probably should break out the bubbles from Iris. We should discuss this in today's meeting I think :)

**Comment by juhaniaa** [comment]
For testing and developing purposes it would be rather problematic to have these bubbles in different repositories, at least now in the beginning.

**Comment by roos-robert** [comment]
Ok! Good, then we keep it like this for now, and break it out when it's possible later on in the developement process. :)
